mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shopping.urls',  namespace='shopping')),
    path('', RedirectView.as_view(url='')),
]

shopping/urls.py
from django.urls import path, include
import django.contrib.auth.urls
from . import views
from shopping.views import products, lat_lng, userFunctions, basket, orders

app_name = 'shopping'

urlpatterns = [
        path('', views.products.product_list, name='product_list'),
        path('product/<int:id>/countries/', views.lat_lng.latLng, name='latLng'),
        path('product/<int:id>/', views.products.product_detail, name= 'product_detail'),
        path('product_new/', views.products.product_new, name= 'product_new'),
        path('product/<int:id>/edit/', views.products.product_edit, name= 'product_edit'),
        path('product/<int:id>/delete/', views.products.product_delete, name= 'product_delete'),

        path('accounts/', include('django.contrib.auth.urls')),
        path('signup/', views.userFunctions.signup, name='signup'),

        path('add_product/<int:product_id>/', views.basket.addProduct, name ='add_product'),
        path('remove_product/<int:product_id>/', views.basket.removeProduct, name ='remove_product'),
        path('basket_detail/', views.basket.basketDetail, name ='basket_detail'),

        path('order_list/', views.orders.order_list, name='order_list'),
        path('order/<int:id>/', views.orders.order_detail, name= 'order_detail'),

        path('payment/', views.userFunctions.Pay, name ='payment'),
        path('purchase/', views.userFunctions.purchase, name ='purchase'),

        path('brand_chart/', views.products.brand_chart, name='brand_chart'),

        path('Pay_successful/', views.userFunctions.Paysuccessful, name='Paysuccessful'),

        path('error/', views.userFunctions.page_not_found, name='error'),
        ]

shopping/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Product Model

class Product(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    brand = models.CharField(max_length=255)
    country_code = models.CharField(max_length=255)
    price = models.FloatField()
    created_date = models.DateTimeField(auto_now_add=True)  

    def __str__(self):
        try:
            return f'{self.name},{self.brand},{self.country_code},{self.price},{self.created_date}'
        except AttributeError as error:
            return "Attributes are missing"

# Country Model

class Country(models.Model):
    product = models.ForeignKey('shopping.Product', on_delete=models.CASCADE, related_name='countries')
    countryCode = models.CharField(max_length=255)
    latitude = models.FloatField()
    longitude = models.FloatField()
    country_name = models.TextField()

    def __str__(self):
        try:
            return f'{self.product},{self.countryCode},{self.latitude},{self.longitude},{self.country_name}'
        except AttributeError as error:
            return "Attributes are missing"


# Customer model

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True,)
    address = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user.email}, {self.address}'

    class Meta:
        db_table = 'customer'

        
    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Customer.objects.create(user=instance)
    
    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.customer.save()

# Cart Model

class Cart(models.Model):
    product = models.ForeignKey('shopping.Product', on_delete=models.CASCADE, related_name='carts')
    quantity = models.IntegerField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        try:
            return f'{self.product},{self.quantity},{self.created_date}'
        except AttributeError as error:
            return "Attributes are missing"

class CartItem(models.Model):
    quantity = models.IntegerField()
    product = models.ForeignKey('shopping.Product', on_delete=models.CASCADE)
    cart = models.ForeignKey('shopping.Cart', on_delete=models.CASCADE)
    order = models.ForeignKey('shopping.Order', on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        try:
            return f'{self.quantity},{self.product},{self.cart},{self.order},{self.created_date}'
        except AttributeError as error:
            return "Attributes are missing"

# Order Model

class Order(models.Model):
    customer = models.ForeignKey('shopping.Customer', on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        try:
            return f'{self.customer},{self.created_date}'
        except AttributeError as error:
            return "Attributes are missing"

shopping/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Product


class ProductForm (forms.ModelForm):
    class Meta:
        model = Product
        fields = ('name','brand','country_code','price',)

class SignUpForm(UserCreationForm):
    username = forms.CharField(max_length=35)
    first_name = forms.CharField(max_length=35)
    last_name = forms.CharField(max_length=35)
    email = forms.EmailField(max_length=50)
    address = forms.CharField()

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 
        'address', 'first_name', 'last_name', )


class ProductForm (forms.ModelForm):
    name= forms.CharField(max_length=200)

    class Meta:
        model = Product
        fields = ('name','price',)

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 100)]

class BasketAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

shopping/views/basket.py
from decimal import Decimal
from django.conf import settings
from django.shortcuts import redirect, render, get_object_or_404
from django.views.decorators.http import require_POST
from shopping.models import Product
from shopping.forms import BasketAddProductForm 

class Basket(object):
    
    def __init__(self, request):
        self.session = request.session
        basket = self.session.get(settings.BASKET_SESSION_ID)      # Get basket information
        if not basket:
            basket = self.session[settings.BASKET_SESSION_ID] = {} # If basket is empty, create an empty
        self.basket = basket                                       # Set basket attribute to current basket

    def __iter__(self):
        print(f'basket: { self.basket }')                          # Iterate through products in the basket
        product_ids = self.basket.keys()
        products = Product.objects.filter(id__in=product_ids)      # Get product objects from the database

        basket = self.basket.copy()
        for product in products:
            basket[str(product.id)]['product'] = product           # Add product object and product id to the basket
            basket[str(product.id)]['product_id'] = product.id

        for item in basket.values():
            item['price'] = Decimal(item['price'])                 # Calculate total price for each basket item
            item['total_price'] = item['price'] * item['quantity']
            yield item

    def __len__(self):                                            
        return sum(item['quantity'] for item in self.basket.values()) # Return the quantity of products in the basket

    def add(self, product, quantity=1, override_quantity=False):
        product_id = str(product.id)
        if product_id not in self.basket:                             # If product is not in basket, add product with its quantity and price
            self.basket[product_id] = {'quantity': 0, 'price': str(product.price)}
        if override_quantity:                                         # Override the current quantity
            self.basket[product_id]['quantity'] = quantity
        else:                                                         # Increase the quantity
            self.basket[product_id]['quantity'] += quantity
        self.save()

    def save(self):
        self.session.modified = True

    def remove(self, product):
        product_id = str(product.id)
        if product_id in self.basket:
            del self.basket[product_id]
            self.save()

    def clear(self):
        del self.session[settings.BASKET_SESSION_ID]
        self.save()

    def get_total_price(self):
        return sum(Decimal(item['price']) * item['quantity'] for item in self.basket.values())

#add product to basket
@require_POST
def addProduct(request, product_id):
    try:
        basket = Basket(request)
        product = get_object_or_404(Product, id=product_id)
        form = BasketAddProductForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            basket.add(product=product,quantity=cd['quantity'],override_quantity=cd['override'])
        return redirect('shopping:basket_detail')
    except Exception as error:
        return render(request, 'error.html')

#remove product from basket
@require_POST
def removeProduct(request, product_id):
    try:
        basket = Basket(request)
        product = get_object_or_404(Product, id=product_id)
        basket.remove(product)
        return redirect('shopping:basket_detail')
    except Exception as error:
        return render(request, 'error.html')

def basketDetail(request):
    try:
        basket = Basket(request)
        for item in basket:
            item['update_quantity_form'] = BasketAddProductForm(initial={'quantity': item['quantity'],'override': True})
        return render(request, 'shopping/basket.html', {'basket': basket})
    except Exception as error:
        return render(request, 'error.html')

shopping/views/lat_lng.py
from django.shortcuts import redirect, render, get_object_or_404
from django.utils import timezone
from django.http import Http404
from shopping.models import Product, Country


def latLng(request, id): 
    product = get_object_or_404(Product, id=id)
    countries = product.countries.all()
    print(countries)
    return render(request, 'shopping/lat_lng.html', {'product': product, 'countries': countries})

shopping/views/orders.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from shopping.models import CartItem, Order

def order_list(request):
    try:
        orders = Order.objects.all()
        return render(request, 'shopping/order_list.html', {'orders' : orders})
    except Exception as error:
        return render(request, 'error.html')

def order_detail(request, id):
    try:
        order = get_object_or_404(Order, id=id)
        customer = order.customer
        user = get_object_or_404(User, id=customer.pk)
        cart_items = CartItem.objects.filter(order_id=order.id)
        return render(request, 'shopping/order_detail.html', {'order' : order, 'user': user, 'cart_items': cart_items})
    except Exception as error:
        return render(request, 'error.html')

shopping/views/products.py
from django.shortcuts import redirect, render, get_object_or_404
from django.utils import timezone
from shopping.forms import ProductForm
from shopping.models import Product, Country
from django.db.models import Count
import plotly.express as px
import plotly.io as pio

"""def product_list(request):                     # no search function
    products = Product.objects.all()    
    return render(request, 'shopping/product_list.html', {'products' : products })"""

def product_list(request):
    brand_query = request.GET.get('brand', '')    # get the brand name for the url
    if brand_query:  
        products = Product.objects.filter(brand__icontains=brand_query)  # achieve case insensitive search
    else:
        products = Product.objects.all()          # if there is no that brand, present all product
    return render(request, 'shopping/product_list.html', {'products': products})


def product_new(request):
    if request.method=="POST":
        form = ProductForm(request.POST)
        if form.is_valid():
            product = form.save(commit=False)    
            product.created_date = timezone.now()
            product.save()
            return redirect('shopping:product_list')
    else:
        form = ProductForm()
    return render(request, 'shopping/product_edit.html', {'form': form})


def product_edit(request, id):
    product = get_object_or_404(Product, id=id)
    if request.method=="POST":
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            product = form.save(commit=False)
            product.created_date = timezone.now()
            product.save()
            return redirect('shopping:product_list')
    else:
        form = ProductForm(instance=product)
    return render(request, 'shopping/product_edit.html', {'form': form})


def product_delete(request, id):
    product = get_object_or_404(Product, id=id)
    deleted = request.session.get('deleted', 'empty')
    request.session['deleted'] = product.name
    product.delete()
    return redirect('shopping:product_list' )


def product_detail(request, id):
    product = get_object_or_404(Product, id=id)
    return render(request, 'shopping/product_detail.html', {'product' : product})


def brand_chart(request):
    data = Product.objects.values('brand').annotate(count=Count('id')).order_by('-count')
    brands = [item['brand'] for item in data]
    counts = [item['count'] for item in data]

    figure = px.bar(x=brands, y=counts, labels={'x': 'Brand', 'y': 'Number of Products'}, title='Number of Products by Brand')    # Generate a bar chart using Plotly（inspired by the example of https://plotly.com/python/bar-charts/）
    barChart_html = pio.to_html(figure, full_html=False)                                                                          # Convert the Plotly figure to HTML

    return render(request, 'shopping/brand_chart.html', {'barChart_html': barChart_html})

shopping/views/userFunctions.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from shopping.models import Product, Cart, Customer, CartItem, Order
from shopping.forms import SignUpForm
from shopping.views.basket import Basket

def signup(request):
    try:
        if request.method == 'POST':
            form = SignUpForm(request.POST)
            if form.is_valid():
                user = form.save()
                user.refresh_from_db()
                user.customer.first_name = form.cleaned_data.get('first_name')
                user.customer.last_name = form.cleaned_data.get('last_name')
                user.customer.address = form.cleaned_data.get('address')
                user.save()
                
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password1')
                user = authenticate(username=username, password=password)
                login(request, user)
                
                return redirect('/')
        else:
            form = SignUpForm()
        return render(request, 'signup.html', {'form': form})
    except form.ValidationError:
        return render(request, 'error.html')
    except Exception as error:
        return render(request, 'error.html')

def Pay(request):
    basket = Basket(request)
    user = request.user
    customer = get_object_or_404(Customer, user_id=user.id)
    order = Order.objects.create(customer=customer)
    order.refresh_from_db()
    for item in basket:
        product_item = get_object_or_404(Product, id=item['product_id'])
        cart = Cart.objects.create(product = product_item, quantity=item['quantity'])
        cart.refresh_from_db()
        cart_item = CartItem.objects.create(quantity=item['quantity'], product=product_item, cart=cart,  order = order)
    basket.clear()
    return redirect('shopping:Paysuccessful' )

def purchase(request):
    if request.user.is_authenticated:
        user = request.user
        basket = Basket(request)
        return render(request, 'shopping/purchase.html', {'basket': basket, 'user': user})
    else:
        return redirect('shopping:login')

def Paysuccessful(request):
    return render(request, 'shopping/pay_successful.html')

def page_not_found(request):
    return render(request, 'error.html')

shopping/templates/shopping/base.html
{% load static %}
<html lang="en">
<head>
    <title> Computer Shopping Station </title>
    <link rel="stylesheet" href="{% static 'cssStyle.css' %}">

</head>

<body>

<div class="normal_links"> 
    <p> 
    
        <a href = "{% url 'shopping:product_list' %}">Home</a> |
        

        {% if user.is_authenticated %}
        <a href = "{% url 'shopping:basket_detail' %}">Basket</a> |
        
        <a href = "{% url 'shopping:logout' %}">Log Out</a> </p>
        {% else %}
        <a href = "{% url 'shopping:login' %}">Log In</a> 
    </p>
        {% endif %}

</div>
    {% block content %}
    {% endblock %}

</body>
</html>

shopping/templates/shopping/basket.html
{% extends 'shopping/base.html' %}
{% block content %}
  <h1>Basket</h1>
 <table>
  {% for item in basket %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{% url 'shopping:product_detail' id=product.id %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url 'shopping:add_product' product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.override }}
                <input type="submit" value="Update">
                {% csrf_token %}
              </form>
            </td>
            <td>
              <form action="{% url 'shopping:remove_product' product.id %}" method="post">
                <input type="submit" value="Remove">
                {% csrf_token %}
              </form>
            </td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">${{ basket.get_total_price }}</td>
      </tr>
  </table>
  <p class="text-right">
    <b><a href="{% url 'shopping:product_list' %}" class="button
    light">Continue shopping</a></b>
  </p>
 
   <b><a href="{% url 'shopping:purchase' %}">Purchase</a></b>
 {% endblock %}

shopping/templates/shopping/brand_chart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Brand Chart</title>
</head>
<body>
    <h1>Brand Chart</h1>
    <div>{{ barChart_html|safe }}</div>
</body>
</html>

shopping/templates/shopping/error.html
{% extends 'shopping/base.html' %}

{% block content %}
    <h1><b>Sorry, there was some problem with the page, please go back and try again.</b></h1>
    <b><a href="{% url 'shopping:product_list' %}" role="button">Continue Shopping</a></b>
    </p>
{% endblock %}

shopping/templates/shopping/lat_lng.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
   integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
   crossorigin=""/>
   <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
   integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
   crossorigin=""></script>
   <style>
     #mapid { height: 660px; }
   </style>
</head>
<body>
  {% if countries %}
        {% for country in countries %}
     <div id="mapid"></div>
      <script type = "text/javascript">
        var mymap = L.map('mapid').setView([{{ country.latitude }}, {{country.longitude}}], 6 );

          accessToken: 'no-token',
        L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
       attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, <a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>',
       maxZoom: 18,
   }).addTo(mymap); 
   var taggingIcon = L.icon({ 
     iconUrl: "{% static 'icons/placeholder-red.png' %} ", 
     iconSize: [35, 35] });
     var marker = L.marker([{{ country.latitude }}, {{country.longitude }}], {icon: taggingIcon }).addTo(mymap);
   </script>
   {% endfor %}
    {% else %}
        <p>No countries found.</p>
    {% endif %}
</body>
</html>

shopping/templates/shopping/order_detail.html
{% extends 'shopping/base.html' %}
{% block content %}
    <h1>Order Details</h1>
    
    <p>Order {{ order.id }} for
      {{user.first_name}} {{user.last_name}}. The order was paid on: {{ order.created_date }} 
   </p>

  {% for cart_item in cart_items %}
    <p>Quantity: {{ cart_item.quantity}} </p>
    <p>Item: {{ cart_item.product }}</p>
  
  
  {% endfor %}
   
    {% endblock %}

shopping/templates/shopping/order_list.html
  {% extends 'shopping/base.html' %}
  {% block content %}
    <h1>Order List</h1>
    
    {% for order in orders %}
    <p>Order Number: <b> <a href="{% url 'shopping:order_detail' id=order.id %}">{{order.id }}</a></b> | The order was paid on: {{ order.created_date }} 
    </p>
    {% endfor %}

    {% endblock %}

shopping/templates/shopping/pay_successful.html
{% extends 'shopping/base.html' %}

{% block content %}
    <h1><b>Thank you for your purchase. Your order is now being processed.</b></h1>
    <b><a href="{% url 'shopping:product_list' %}" role="button">Continue Shopping</a></b>
    </p>
{% endblock %}

shopping/templates/shopping/product_detail.html
{% extends 'shopping/base.html' %}
{% block content %}
    <h1>Product Details</h1>
    <div class="product">
        <p><b>{{ product.name }}
        <br>Price: {{product.price}}.
        <br>Sold from <a href="{% url 'shopping:latLng' id=product.id %}">{{ product.country_code }}</a>.
        <br>The product was created on: {{ product.created_date }}. </b></p>

        </p>
    </div>

    <form action="{% url 'shopping:add_product' product.id %}" method="post">
        {% csrf_token %}
        <label for="quantity">Quantity:</label>
        <input type="number" name="quantity" id="quantity" value="1" min="1" max="100">
        <input type="hidden" name="override" value="False">
        <button type="submit">Add to Cart</button>
    </form>
    {% if request.user.is_superuser %}
        <p><b><a href="{% url 'shopping:product_delete' id=product.id %}">Delete the product</a></b></p>
        <p><b><a href="{% url 'shopping:product_edit' id=product.id %}">Edit</a></b></p>
    {% endif %}
    {% endblock %}
    

shopping/templates/shopping/product_edit.html
{% extends 'shopping/base.html' %}
{% block content %}
    <h1>Product Edit</h1>
    <p>Product:
    <form method="POST"> 
        {% csrf_token %}
        {{ form.as_p}}
        <button type="submit" name="submit">Save</button>
   </p>
   </form>
    {% endblock %}

shopping/templates/shopping/product_list.html
{% extends 'shopping/base.html' %}
{% block content %}

<h1>Welcome To Computer Shopping Station</h1>

<form method="get" action="">
    <input type="text" name="brand" placeholder="Searching by brand name" value="{{ request.GET.brand }}">
    <button type="submit">Search</button>
</form>

{% if request.user.is_superuser %}
<div class="admin-links">
    <a href="{% url 'shopping:brand_chart' %}">View Brand Chart</a> |
    <a href="{% url 'shopping:product_new' %}">Add a new product</a> |
    <a href="{% url 'shopping:order_list' %}">Orders</a>
</div>
{% endif %}

{% for product in products %}
<div class="product">
    <p>
        This is product {{ product.id }} 
        <b><a href="{% url 'shopping:product_detail' id=product.id %}">{{ product.name }}</a></b>
        | Price: {{ product.price }}. | <b>Brand: {{ product.brand }}</b>. | The product was added on: {{ product.created_date }} |
    </p>
</div>
{% endfor %}

{% endblock %}

shopping/templates/shopping/purchase.html
{% extends 'shopping/base.html' %}
{% block content %}
    <h1>Your Order</h1>
    
<h2>Basket:</h2>
  {% for item in basket %}
    {% with product=item.product %}
 
<p><b> {{ product.name }}</b></p>
     {% endwith %}
   {% endfor %}
 <p><b>Total Price: {{ basket.get_total_price }} </b></p>
   <p>
    <form action="/payment/" method="post">
       {% csrf_token %}
       <label for 'pay'>Card Information:</label><input type='text' size=5 name='payment'>
       <input type="number" name="total" value="Total Payment:">
       <input type="submit" value="Payment">
       </form>
       </p>
 {% endblock %}